typescript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'

'Type: Testing':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.spec.ts'
      - '**/*.e2e-spec.ts'

'Type: Documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'

'Type: CI/CD':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/*.yml'
