export const DITokens = {
  PrismaClient: 'PrismaClient',
  Repository: 'Repository',
  SSOClient: 'SSOClient',
  Policies: 'Policies',
  UserSessionProvider: 'UserSessionProvider',
  HandleErrorUseCase: 'HandleErrorUseCase',
  HandleErrorNotifications: 'HandleErrorNotifications',
  HandleErrorPresenter: 'HandleErrorPresenter',

  TaskRepository: 'TaskRepository',
  TaskPolicy: 'TaskPolicy',
  FetchTaskUseCase: 'FetchTaskUseCase',
  PaginateTaskQueryService: 'PaginateTaskQueryService',
  CreateTaskUseCase: 'CreateTaskUseCase',
  DeleteTaskUseCase: 'DeleteTaskUseCase',
  UpdateTaskUseCase: 'UpdateTaskUseCase',
  OnCompleteTaskUseCase: 'OnCompleteTaskUseCase',
  OnStartTaskUseCase: 'OnStartTaskUseCase',
  TaskPresenter: 'TaskPresenter',
  TaskQueryServicePresenter: 'TaskQueryServicePresenter',

  UserRepository: 'UserRepository',
  UserPolicy: 'UserPolicy',
  FetchMeUseCase: 'FetchMeUseCase',
  FetchUserUseCase: 'FetchUserUseCase',
  PaginateUserQueryService: 'PaginateUserQueryService',
  CreateUserUseCase: 'CreateUserUseCase',
  DeleteUserUseCase: 'DeleteUserUseCase',
  UpdateUserUseCase: 'UpdateUserUseCase',
  UserPresenter: 'UserPresenter',
  UserQueryServicePresenter: 'UserQueryServicePresenter',
} as const;
