on:
  issues:
    types: [opened]

name: Issue opened

jobs:
  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/assign-author@v1
